import { exec } from 'child_process';
import { promisify } from 'util';
import * as fs from 'fs/promises';
import * as path from 'path';

const execAsync = promisify(exec);

const NGINX_SITES_AVAILABLE = process.env.NGINX_SITES_AVAILABLE || '/etc/nginx/sites-available';
const NGINX_SITES_ENABLED = process.env.NGINX_SITES_ENABLED || '/etc/nginx/sites-enabled';
const STATIC_SITES_PATH = process.env.STATIC_SITES_PATH || '/var/www/sites';
const BASE_DOMAIN = process.env.BASE_DOMAIN || 'aksi.info';

// Generate Nginx server block configuration
export function generateNginxConfig(subdomain: string): string {
    const fullDomain = `${subdomain}.${BASE_DOMAIN}`;
    const rootPath = path.join(STATIC_SITES_PATH, subdomain);

    return `# Nginx config for ${fullDomain}
# Generated by SEO Super App

server {
    listen 80;
    listen [::]:80;
    server_name ${fullDomain};
    
    # Redirect HTTP to HTTPS
    return 301 https://$server_name$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name ${fullDomain};
    
    # SSL certificates (managed by Certbot)
    ssl_certificate /etc/letsencrypt/live/${BASE_DOMAIN}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${BASE_DOMAIN}/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
    
    root ${rootPath};
    index index.html;
    
    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    
    # Caching for static assets
    location ~* \\.(css|js|jpg|jpeg|png|gif|ico|svg|woff|woff2)$ {
        expires 30d;
        add_header Cache-Control "public, immutable";
    }
    
    # HTML pages - shorter cache
    location ~* \\.html$ {
        expires 1h;
        add_header Cache-Control "public, must-revalidate";
    }
    
    # Main location
    location / {
        try_files $uri $uri/ $uri.html =404;
    }
    
    # Custom 404 page
    error_page 404 /index.html;
    
    # Gzip compression
    gzip on;
    gzip_vary on;
    gzip_min_length 1024;
    gzip_types text/plain text/css text/xml text/javascript application/javascript application/xml application/json;
    
    # Logging
    access_log /var/log/nginx/${subdomain}.access.log;
    error_log /var/log/nginx/${subdomain}.error.log;
}
`;
}

// Generate simple HTTP-only config (for initial setup before SSL)
export function generateNginxConfigHTTPOnly(subdomain: string): string {
    const fullDomain = `${subdomain}.${BASE_DOMAIN}`;
    const rootPath = path.join(STATIC_SITES_PATH, subdomain);

    return `# Nginx config for ${fullDomain} (HTTP only - pre-SSL)
# Generated by SEO Super App

server {
    listen 80;
    listen [::]:80;
    server_name ${fullDomain};
    
    root ${rootPath};
    index index.html;
    
    # For Let's Encrypt validation
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
    
    location / {
        try_files $uri $uri/ $uri.html =404;
    }
    
    error_page 404 /index.html;
    
    gzip on;
    gzip_types text/plain text/css text/xml text/javascript application/javascript application/xml;
    
    access_log /var/log/nginx/${subdomain}.access.log;
    error_log /var/log/nginx/${subdomain}.error.log;
}
`;
}

// Create Nginx configuration file
export async function createSubdomainConfig(
    subdomain: string,
    useSSL: boolean = true
): Promise<void> {
    const configPath = path.join(NGINX_SITES_AVAILABLE, subdomain);
    const config = useSSL
        ? generateNginxConfig(subdomain)
        : generateNginxConfigHTTPOnly(subdomain);

    await fs.writeFile(configPath, config, 'utf-8');
    console.log(`Created Nginx config: ${configPath}`);
}

// Enable site by creating symlink
export async function enableSite(subdomain: string): Promise<void> {
    const availablePath = path.join(NGINX_SITES_AVAILABLE, subdomain);
    const enabledPath = path.join(NGINX_SITES_ENABLED, subdomain);

    try {
        // Check if symlink already exists
        await fs.access(enabledPath);
        console.log(`Site ${subdomain} already enabled`);
    } catch {
        // Create symlink
        await fs.symlink(availablePath, enabledPath);
        console.log(`Enabled site: ${subdomain}`);
    }
}

// Disable site by removing symlink
export async function disableSite(subdomain: string): Promise<void> {
    const enabledPath = path.join(NGINX_SITES_ENABLED, subdomain);

    try {
        await fs.unlink(enabledPath);
        console.log(`Disabled site: ${subdomain}`);
    } catch {
        console.log(`Site ${subdomain} was not enabled`);
    }
}

// Test Nginx configuration
export async function testNginxConfig(): Promise<boolean> {
    try {
        await execAsync('sudo nginx -t');
        console.log('Nginx configuration test passed');
        return true;
    } catch (error) {
        console.error('Nginx configuration test failed:', error);
        return false;
    }
}

// Reload Nginx to apply changes
export async function reloadNginx(): Promise<void> {
    try {
        await execAsync('sudo nginx -s reload');
        console.log('Nginx reloaded successfully');
    } catch (error) {
        console.error('Failed to reload Nginx:', error);
        throw error;
    }
}

// Create site directory
export async function createSiteDirectory(subdomain: string): Promise<string> {
    const sitePath = path.join(STATIC_SITES_PATH, subdomain);
    await fs.mkdir(sitePath, { recursive: true });
    console.log(`Created site directory: ${sitePath}`);
    return sitePath;
}

// Full deployment process
export async function deploySite(
    subdomain: string,
    localOutputDir: string,
    useSSL: boolean = true
): Promise<void> {
    console.log(`Starting deployment for ${subdomain}...`);

    // 1. Create site directory on server
    const sitePath = await createSiteDirectory(subdomain);

    // 2. Copy files from local output to server directory
    await execAsync(`sudo cp -r ${localOutputDir}/* ${sitePath}/`);
    console.log(`Copied files to ${sitePath}`);

    // 3. Set proper permissions
    await execAsync(`sudo chown -R www-data:www-data ${sitePath}`);
    await execAsync(`sudo chmod -R 755 ${sitePath}`);
    console.log('Set file permissions');

    // 4. Create Nginx config
    await createSubdomainConfig(subdomain, useSSL);

    // 5. Enable the site
    await enableSite(subdomain);

    // 6. Test Nginx config
    const configValid = await testNginxConfig();
    if (!configValid) {
        // Rollback
        await disableSite(subdomain);
        throw new Error('Nginx configuration is invalid');
    }

    // 7. Reload Nginx
    await reloadNginx();

    console.log(`✅ Deployment complete: https://${subdomain}.${BASE_DOMAIN}`);
}

// Check if deployment tools are available
export async function checkDeploymentPrerequisites(): Promise<{
    nginx: boolean;
    sudo: boolean;
    sitesPath: boolean;
}> {
    const results = {
        nginx: false,
        sudo: false,
        sitesPath: false,
    };

    try {
        await execAsync('which nginx');
        results.nginx = true;
    } catch { /* nginx not found */ }

    try {
        await execAsync('sudo -n true');
        results.sudo = true;
    } catch { /* sudo requires password */ }

    try {
        await fs.access(NGINX_SITES_AVAILABLE);
        results.sitesPath = true;
    } catch { /* sites-available not accessible */ }

    return results;
}

// Generate deployment script for manual execution
export function generateDeploymentScript(subdomain: string): string {
    const fullDomain = `${subdomain}.${BASE_DOMAIN}`;
    const sitePath = path.join(STATIC_SITES_PATH, subdomain);

    return `#!/bin/bash
# Deployment script for ${fullDomain}
# Generated by SEO Super App

set -e

echo "Deploying ${fullDomain}..."

# Create site directory
sudo mkdir -p ${sitePath}

# Copy files (run this from your local machine or adjust path)
# sudo cp -r ./output/${subdomain}/* ${sitePath}/

# Set permissions
sudo chown -R www-data:www-data ${sitePath}
sudo chmod -R 755 ${sitePath}

# Create Nginx config
sudo tee ${NGINX_SITES_AVAILABLE}/${subdomain} > /dev/null << 'EOF'
${generateNginxConfigHTTPOnly(subdomain)}
EOF

# Enable site
sudo ln -sf ${NGINX_SITES_AVAILABLE}/${subdomain} ${NGINX_SITES_ENABLED}/${subdomain}

# Test and reload Nginx
sudo nginx -t
sudo nginx -s reload

# Obtain SSL certificate (uncomment after DNS is configured)
# sudo certbot --nginx -d ${fullDomain}

echo "✅ Deployment complete!"
echo "Site available at: http://${fullDomain}"
echo ""
echo "Next steps:"
echo "1. Ensure DNS A record points ${fullDomain} to your server IP"
echo "2. Run: sudo certbot --nginx -d ${fullDomain}"
`;
}
